name = "SaltyMon Unleashed"
author = "Saltytacozzz"
version = "1.1.67"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "961507c5532ad8b7cbff37b0de2a856a92b95a6064ec8fa318f8a1ddb73998a7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
