name = "SaltyMon Unleashed"
author = "Saltytacozzz"
version = "1.1.67"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a8473e21d31e1983d19f545a005ebdba05f54aeb93603e373b083a338be583c7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
