name = "SaltyMon Unleashed"
author = "Saltytacozzz"
version = "1.0.21"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d7af4eda70a61762d16a4d4c90ab84dc52f1687d8447ea642dc83566437a9e4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
