#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Aug 23 20:52:39 MDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=
