#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Aug 28 00:32:14 MDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
