#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Aug 25 06:25:33 MDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=
